# Generated by Django 5.2 on 2025-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Фамилия пользователя",
            ),
        ),
    ]
