# Generated by Django 5.2 on 2025-05-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_token"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
