# Generated by Django 5.2 on 2025-05-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="advertisement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="advertisements.advertisement",
                verbose_name="Объявление",
            ),
        ),
    ]
